-- University Management System — Sprint 1 only (Supabase PostgreSQL)
create table if not exists users (
 id bigserial primary key, username varchar(80) not null unique, email varchar(255) unique,
 password_hash varchar(128) not null, role varchar(20) not null default 'STUDENT'
   check (role in ('ADMIN','STUDENT','PROFESSOR','STAFF')), active boolean not null default true,
 created_at timestamptz not null default now()
);
create index if not exists idx_users_email on users(email);

create table if not exists rooms (
 id bigserial primary key, room_code varchar(40) not null unique, name varchar(160) not null,
 type varchar(20) not null check (type in ('CLASSROOM','LAB','OFFICE','CONFERENCE')),
 capacity integer not null check (capacity > 0), location varchar(160) not null,
 status varchar(20) not null default 'AVAILABLE' check (status in ('AVAILABLE','OCCUPIED','MAINTENANCE')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_rooms_code on rooms(room_code);
create index if not exists idx_rooms_status on rooms(status);

create table if not exists maintenance_tickets (
 id bigserial primary key, room_id bigint not null references rooms(id) on delete restrict,
 reporter_id bigint not null references users(id) on delete restrict,
 assigned_to bigint references users(id) on delete set null,
 description text not null check (length(trim(description)) > 0),
 status varchar(20) not null default 'PENDING' check (status in ('PENDING','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_tickets_reporter on maintenance_tickets(reporter_id);
create index if not exists idx_tickets_room on maintenance_tickets(room_id);

create table if not exists courses (
 id bigserial primary key, code varchar(30) not null unique, name varchar(180) not null,
 description text, credits integer not null check (credits > 0 and credits <= 12),
 department varchar(100), semester varchar(40), type varchar(20) not null check (type in ('CORE','ELECTIVE')),
 capacity integer not null check (capacity > 0), active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_courses_code on courses(code);

create table if not exists course_prerequisites (
 course_id bigint not null references courses(id) on delete cascade,
 prerequisite_course_id bigint not null references courses(id) on delete restrict,
 primary key(course_id, prerequisite_course_id), check(course_id <> prerequisite_course_id)
);

create table if not exists enrollments (
 id bigserial primary key, student_id bigint not null references users(id) on delete restrict,
 course_id bigint not null references courses(id) on delete restrict,
 enrolled_at timestamptz not null default now(), status varchar(20) not null default 'ENROLLED'
   check(status in ('ENROLLED','DROPPED','COMPLETED','FAILED')),
 unique(student_id, course_id)
);
create index if not exists idx_enrollments_student on enrollments(student_id);
create index if not exists idx_enrollments_course on enrollments(course_id);

create table if not exists course_room_assignments (
 id bigserial primary key, course_id bigint not null references courses(id) on delete restrict,
 room_id bigint not null references rooms(id) on delete restrict,
 day_of_week varchar(12), start_time time, end_time time,
 created_at timestamptz not null default now(),
 check ((start_time is null and end_time is null) or (start_time is not null and end_time is not null and start_time < end_time))
);
create index if not exists idx_assignments_course on course_room_assignments(course_id);
create index if not exists idx_assignments_room on course_room_assignments(room_id);

-- Optional seed examples. Replace passwords with SHA-256 hashes generated by AuthService.
-- insert into users(username,password_hash,role) values ('admin','<sha256>','ADMIN');
