package edu.facilities.service;
import edu.facilities.model.*; import java.sql.*; import java.time.*; import java.util.*;
public class CourseService {
 private Course map(ResultSet r)throws SQLException{Course c=new Course(String.valueOf(r.getLong("id")),r.getString("code"),r.getString("name"),r.getString("description"),r.getInt("credits"),r.getString("department"),r.getString("semester"),CourseType.valueOf(r.getString("type")),r.getInt("capacity"),r.getInt("enrolled"),r.getBoolean("active"),r.getTimestamp("created_at").toLocalDateTime(),r.getTimestamp("updated_at").toLocalDateTime());return c;}
 public List<Course> getAllCourses(boolean active)throws SQLException{return filter(null,null,null,active);}
 public List<Course> filter(String department,String semester,CourseType type,boolean active)throws SQLException{List<Course>out=new ArrayList<>();String sql="select c.*,count(e.id) filter(where e.status='ENROLLED') enrolled from courses c left join enrollments e on e.course_id=c.id where (? is null or c.department=?) and (? is null or c.semester=?) and (? is null or c.type=?) and (?=false or c.active=true) group by c.id order by c.code";try(Connection x=DatabaseConnection.getConnection();PreparedStatement s=x.prepareStatement(sql)){s.setString(1,department);s.setString(2,department);s.setString(3,semester);s.setString(4,semester);s.setString(5,type==null?null:type.name());s.setString(6,type==null?null:type.name());s.setBoolean(7,active);try(ResultSet r=s.executeQuery()){while(r.next())out.add(map(r));}}return out;}
 public List<Course> search(String q)throws SQLException{List<Course>out=new ArrayList<>();try(Connection x=DatabaseConnection.getConnection();PreparedStatement s=x.prepareStatement("select c.*,count(e.id) filter(where e.status='ENROLLED') enrolled from courses c left join enrollments e on e.course_id=c.id where c.active=true and (lower(c.code) like lower(?) or lower(c.name) like lower(?)) group by c.id order by c.code")){String v="%"+q+"%";s.setString(1,v);s.setString(2,v);try(ResultSet r=s.executeQuery()){while(r.next())out.add(map(r));}}return out;}
 public List<String> getAllDepartments()throws SQLException{return distinct("department");} public List<String> getAllSemesters()throws SQLException{return distinct("semester");}
 private List<String> distinct(String col)throws SQLException{List<String>o=new ArrayList<>();try(Connection c=DatabaseConnection.getConnection();PreparedStatement s=c.prepareStatement("select distinct "+col+" from courses where active=true order by 1");ResultSet r=s.executeQuery()){while(r.next())o.add(r.getString(1));}return o;}
}
