package edu.facilities.service;
import edu.facilities.model.*;
import java.sql.*; import java.util.*;
public class RoomService {
    private Room map(ResultSet r) throws SQLException { return new Room(String.valueOf(r.getLong("id")), r.getString("name"), RoomType.valueOf(r.getString("type")), r.getInt("capacity"), r.getString("location"), RoomStatus.valueOf(r.getString("status"))); }
    public List<Room> getAllRooms() throws SQLException { List<Room> out=new ArrayList<>(); try(Connection c=DatabaseConnection.getConnection(); PreparedStatement s=c.prepareStatement("select id,room_code as name,name as location,type,capacity,location,status from rooms order by room_code"); ResultSet r=s.executeQuery()){while(r.next()) out.add(map(r));} return out; }
    public List<Room> getAvailableRooms() throws SQLException { return query("where status='AVAILABLE'"); }
    private List<Room> query(String where) throws SQLException { List<Room> out=new ArrayList<>(); try(Connection c=DatabaseConnection.getConnection(); PreparedStatement s=c.prepareStatement("select id,room_code as name,name as location,type,capacity,location,status from rooms "+where+" order by room_code"); ResultSet r=s.executeQuery()){while(r.next()) out.add(map(r));} return out; }
    public void createRoom(String code,String name,RoomType type,int capacity,String location,RoomStatus status) throws SQLException { requireAdmin(); validate(code,name,capacity); try(Connection c=DatabaseConnection.getConnection(); PreparedStatement s=c.prepareStatement("insert into rooms(room_code,name,type,capacity,location,status) values(?,?,?,?,?,?)")){s.setString(1,code.trim());s.setString(2,name.trim());s.setString(3,type.name());s.setInt(4,capacity);s.setString(5,location.trim());s.setString(6,status.name());s.executeUpdate();} }
    public void updateRoom(String code,String name,RoomType type,int capacity,String location,RoomStatus status) throws SQLException { requireAdmin(); validate(code,name,capacity); try(Connection c=DatabaseConnection.getConnection(); PreparedStatement s=c.prepareStatement("update rooms set name=?,type=?,capacity=?,location=?,status=? where room_code=?")){s.setString(1,name.trim());s.setString(2,type.name());s.setInt(3,capacity);s.setString(4,location.trim());s.setString(5,status.name());s.setString(6,code.trim());if(s.executeUpdate()==0) throw new SQLException("Room not found");} }
    public boolean deleteRoom(String code) throws SQLException { requireAdmin(); try(Connection c=DatabaseConnection.getConnection(); PreparedStatement s=c.prepareStatement("delete from rooms where room_code=?")){s.setString(1,code);return s.executeUpdate()==1;} }
    public Room findById(String id) throws SQLException { try(Connection c=DatabaseConnection.getConnection(); PreparedStatement s=c.prepareStatement("select id,room_code as name,name as location,type,capacity,location,status from rooms where id=?")){s.setLong(1,Long.parseLong(id));try(ResultSet r=s.executeQuery()){return r.next()?map(r):null;}} }
    private void requireAdmin(){if(!AuthService.getInstance().hasRole("ADMIN"))throw new SecurityException("Only administrators can manage room records.");}
    private void validate(String code,String name,int capacity){if(code==null||code.isBlank()||name==null||name.isBlank()||capacity<=0)throw new IllegalArgumentException("Room code, name and positive capacity are required.");}
}
